version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: todolist-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: todolist
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
    networks:
      - todolist-network

volumes:
  postgres-data:

networks:
  todolist-network:
